name: Almog-Omer-Kobi-CI

# Controls when the workflow will run (EVENTS)
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    name: Unit Test API Gateway
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python3.13 and install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt

      - name: Running Unit Test
        run: |
          pytest test.py
